// Minimal ko + en map for Phase 0. UI mostly in Korean per UI_UX_SPEC §1.

export const STRINGS = {
  ko: {
    app_name: "Truth & Strike",
    url_bar_placeholder: "주소를 입력하거나 검색어를 입력하세요",
    drawer_title: "설정",
    drawer_close: "닫기",
    find_placeholder: "페이지에서 찾기",
    new_tab: "새 탭",
    close_tab: "탭 닫기",
    new_tab_title: "새 탭",
    // Drawer sections
    section_llm: "LLM",
    section_search: "검색",
    section_vibe: "Vibe",
    section_privacy: "개인정보",
    section_about: "정보",
    // Fields
    field_provider: "제공자",
    field_model: "모델",
    field_api_key: "API 키",
    field_test: "연결 테스트",
    field_save: "저장",
    field_clear: "삭제",
    // Privacy
    clear_browsing_data: "방문 기록 삭제",
    clear_stored_keys: "저장된 키 삭제",
    reset_all: "모두 초기화",
    // Banners
    keychain_unavailable:
      "OS 키체인을 사용할 수 없습니다. 키는 메모리에만 저장되며 종료 시 사라집니다.",
    no_api_key_tooltip: "API 키를 먼저 설정에서 입력하세요",
    // Welcome
    welcome_title: "Truth & Strike",
    welcome_subtitle: "온라인 토론을 위한 작은 브라우저",
    welcome_body:
      "시작하려면 우측 ✦ 버튼을 눌러 API 키를 입력하세요. 자세한 내용은 우상단 설정에서 확인할 수 있습니다.",
    welcome_open_settings: "설정 열기",
    welcome_privacy:
      "키는 OS 키체인에 암호화되어 저장됩니다. 텔레메트리는 없고, 페이지 내용은 사용자가 명시적으로 🛡 / ⚔ 를 누를 때만 LLM 으로 전송됩니다.",
    // Agent panel
    btn_defense: "🛡 Defense",
    btn_attack: "⚔ Attack",
    chat_placeholder: "주장이나 초안을 입력하세요. 페이지에서 텍스트 선택 후 버튼을 눌러도 됩니다.",
    chat_send: "전송",
    panel_close: "닫기",
    panel_collapse: "접기",
    panel_regenerate: "다시 생성",
    panel_idle: "Idle",
    panel_idle_hint:
      "우측 사이드바의 Defense / Attack / Fact Check 를 누르거나, 페이지에서 텍스트를 선택 후 우클릭하세요.",
    // Verdict labels
    verdict_true: "사실",
    verdict_false: "거짓",
    verdict_mixed: "부분적 사실",
    verdict_unverifiable: "확인 불가",
    // Stages
    stage_loading: "준비 중…",
    stage_vibe_lookup: "사이트 분위기 파악 중…",
    stage_fact_check: "사실 확인 중…",
    stage_logic_detect: "논리 점검 중…",
    stage_vibe_rewrite: "톤 적용 중…",
    stage_evaluator_score: "점수 매기는 중…",
    stage_vibe_finalize: "최종 글 다듬는 중…",
    stage_refine_rewrite: "다시 쓰는 중…",
    // Errors
    err_no_api_key: "API 키가 필요합니다. 설정에서 입력하세요.",
    err_llm_unreachable: "LLM 서버에 연결할 수 없습니다.",
    err_search_unreachable: "검색 서버에 연결할 수 없습니다.",
    err_timeout: "응답이 너무 오래 걸렸습니다.",
    err_cancelled: "취소되었습니다.",
    err_unknown: "알 수 없는 오류가 발생했습니다.",
    retry: "다시 시도",
    // Sources
    sources_label: "출처",
    no_sources: "출처를 찾지 못했습니다 — LLM 추정",
    copy: "복사",
    copied: "복사됨",
    open_link: "링크 열기",
    // Sidebar
    sidebar_open: "사이드바 열기",
    sidebar_close: "사이드바 닫기",
    sidebar_new_chat: "새 대화",
    sidebar_search: "주소창",
    sidebar_fact_check: "Fact Check",
    sidebar_defense: "🛡 Defense",
    sidebar_attack: "⚔ Attack",
    sidebar_settings: "설정",
    sidebar_agents: "에이전트",
    sidebar_workspace: "워크스페이스",
  },
  en: {
    app_name: "Truth & Strike",
    url_bar_placeholder: "Type a URL or a search query",
    drawer_title: "Settings",
    drawer_close: "Close",
    find_placeholder: "Find in page",
    new_tab: "New Tab",
    close_tab: "Close Tab",
    new_tab_title: "New Tab",
    section_llm: "LLM",
    section_search: "Search",
    section_vibe: "Vibe",
    section_privacy: "Privacy",
    section_about: "About",
    field_provider: "Provider",
    field_model: "Model",
    field_api_key: "API Key",
    field_test: "Test connection",
    field_save: "Save",
    field_clear: "Clear",
    clear_browsing_data: "Clear browsing data",
    clear_stored_keys: "Clear stored keys",
    reset_all: "Reset all settings",
    keychain_unavailable:
      "OS keychain unavailable. Keys are held in memory only and cleared on quit.",
    no_api_key_tooltip: "Set API key in Settings first",
    welcome_title: "Truth & Strike",
    welcome_subtitle: "A small browser for online debate",
    welcome_body:
      "To start, click the ✦ on the right edge and enter your API key.",
    welcome_open_settings: "Open Settings",
    welcome_privacy:
      "Keys are encrypted in the OS keychain. No telemetry. Page content is sent to the LLM only when you explicitly click 🛡 / ⚔.",
    btn_defense: "🛡 Defense",
    btn_attack: "⚔ Attack",
    chat_placeholder:
      "Type a claim or draft. You can also select text on the page and click a button.",
    chat_send: "Send",
    panel_close: "Close",
    panel_collapse: "Collapse",
    panel_regenerate: "Regenerate",
    panel_idle: "Idle",
    panel_idle_hint:
      "Click Defense / Attack / Fact Check in the right sidebar, or select text on the page and right-click.",
    verdict_true: "True",
    verdict_false: "False",
    verdict_mixed: "Partial",
    verdict_unverifiable: "Unverified",
    stage_loading: "Preparing…",
    stage_vibe_lookup: "Reading site vibe…",
    stage_fact_check: "Fact-checking…",
    stage_logic_detect: "Checking logic…",
    stage_vibe_rewrite: "Applying tone…",
    stage_evaluator_score: "Scoring…",
    stage_vibe_finalize: "Finalizing…",
    stage_refine_rewrite: "Rewriting…",
    err_no_api_key: "API key required. Set it in Settings.",
    err_llm_unreachable: "Cannot reach LLM server.",
    err_search_unreachable: "Cannot reach search server.",
    err_timeout: "The request took too long.",
    err_cancelled: "Cancelled.",
    err_unknown: "Unknown error.",
    retry: "Retry",
    sources_label: "Sources",
    no_sources: "No sources found — LLM-only assertion",
    copy: "Copy",
    copied: "Copied",
    open_link: "Open link",
    sidebar_open: "Open sidebar",
    sidebar_close: "Close sidebar",
    sidebar_new_chat: "New chat",
    sidebar_search: "Address bar",
    sidebar_fact_check: "Fact Check",
    sidebar_defense: "🛡 Defense",
    sidebar_attack: "⚔ Attack",
    sidebar_settings: "Settings",
    sidebar_agents: "Agents",
    sidebar_workspace: "Workspace",
  },
} as const;

export type Locale = keyof typeof STRINGS;
export const DEFAULT_LOCALE: Locale = "ko";

export function t(key: keyof (typeof STRINGS)["ko"], locale: Locale = DEFAULT_LOCALE): string {
  return STRINGS[locale][key];
}
